config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books do
    resources :likes, only: [:create, :destroy]
    resources :wants, only: [:create, :destroy]
    resources :comments
    resources :results
    
  end

  resources :perfumes


    root 'books#index'

  get "books/:id/success" => "books#success", as:"success_book"
  get "books/:book_id/likes" => 'likes#create'
  get "books/:book_id/likes/:id" => 'likes#destroy'

  get "books/:book_id/wants" => 'wants#create'
  get "books/:book_id/wants/:id" => 'wants#destroy'

  post 'perfumes/:num' => 'perfumes#result'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :wants, dependent: :destroy
    has_many :wanted_users, through: :wants, source: :user

    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/perfume.rb
class Perfume < ApplicationRecord
    belongs_to :user 
end

app/models/result.rb
class Result < ApplicationRecord

    belongs_to :user 
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_books, through: :likes, source: :book

  has_many :wants, dependent: :destroy
  has_many :wanted_books, through: :wants, source: :book

  has_many :comments, dependent: :destroy

  # has_many :perfumes, dependent: :destroy
  # has_many :resulted_perfumes, through: :results, source: :book

  has_many :results, dependent: :destroy
  has_many :perfumes, dependent: :destroy


  def already_liked?(book)
    self.likes.exists?(book_id: book.id)
  end

  def already_wanted?(book)
    self.wants.exists?(book_id: book.id)
  end

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def index
        @books = Book.all
        @liked = Book.includes(:liked_users).limit(3).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
        @wanted = Book.includes(:wanted_users).limit(3).sort {|a,b| b.wanted_users.size <=> a.wanted_users.size}
 
     if params[:search] == nil
         @books= Book.all
     elsif params[:search] == ''
         @books= Book.all
     else
          #部分検索
         @books = Book.where("movie LIKE ? or point LIKE?",'%' + params[:search] + '%','%' + params[:search] + '%')
     end

    end
      
    def new
        @book = Book.new
    end
    
    def create
        book = Book.new(book_params)
        book.user_id = current_user.id
        if book.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @book = Book.find(params[:id])

        @comments = @book.comments
        @comment = Comment.new
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        book = Book.find(params[:id])
        if book.update(book_params)
            redirect_to :action => "success", :id => book.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        book = Book.find(params[:id])
        # book変数の中にBook.find(params[:id])が代入されている
        book.destroy
        # それをdestroyする
        redirect_to action: :index
    end

    private
    def book_params
        params.require(:book).permit(:story, :movie, :year, :title, :image, :point)
    end

end

# commentコントローラーとcommentコントローラーを削除し、やり直す

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      book = Book.find(params[:book_id])
      comment = book.comments.build(comment_params) #buildを使い、contentとbook_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end

    def destroy
      comment = Comment.find(params[:book_id])
      comment.destroy
      redirect_back(fallback_location: root_path)
  end

  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
        
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(book_id: params[:book_id]) #user_idとbook_idの二つを代入
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(book_id: params[:book_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  
  end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end
  
    def new
      @perfume = Perfume.new
    end
  
    def show
      @perfume = Perfume.find_by(id: params[:id])
    end
  
    def create
      @perfume = Perfume.new(perfume_params)

      @perfume.user_id = current_user.id

      params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
      if @perfume.save
          flash[:notice] = "診断が完了しました"
          redirect_to perfume_path(@perfume.id)
      else
          redirect_to :action => "new"
      end
    end

    def result
       num = params[:num]
       result = Result.new
       result.number = num
       result.user_id = current_user.id

       if result.save
          @result = num
          @perfumes = Perfume.all
          render "perfumes/index"
       else
          redirect_to root_path
    end


   end
  
  private
    def perfume_params
        params.require(:perfume).permit(:id, question: [])
    end
  end

app/controllers/result_controller.rb
class ResultController < ApplicationController

    def new
        @result = Result.new
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
        @perfumes = Perfume.all
    end

end

app/controllers/wants_controller.rb
class WantsController < ApplicationController

    def create
        want = current_user.wants.create(book_id: params[:book_id]) #user_idとbook_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        want = Want.find_by(book_id: params[:book_id], user_id: current_user.id)
        want.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/books/edit.html.erb
<h1>Isaka kotaro</h1>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :size => 140 %> 

  <%= f.label :story %>
  <%= f.text_field :story, :size => 140 %> 

  <%= f.submit "編集する" %>
<% end %>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
    <head>
    <title>Isaka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'books', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    </head>

    <div id="search">
    <h3>映画化</h3>
    <%= form_tag({controller:"books",action:"index"}, method: :get) do %>
    <%= select_tag :search , raw("<option>選択してください</option><option>している</option><option>していない</option>"), id: 'classes' %>
    <%= submit_tag '検索する'  %>
    <% end %>
    </div>

    <div id="search">
    <h3>特徴</h3>
    <%= form_tag({controller:"books",action:"index"}, method: :get) do %>
    <%= select_tag :search , raw("<option>選択してください</option><option>叙述トリック</option><option>エッセイ</option><option>陣内シリーズ</option><option>殺し屋シリーズ</option><option>陽気なギャグシリーズ</option><option>登場人物が特徴的</option><option>群像劇</option><option>短編集</option><option>連作短編集</option><option>中編集</option><option>長編</option><option>合作</option><option>挿絵</option><option>黒澤</option><option>田中</option><option>疾走感</option>"), id: 'classes' %>
    <%= submit_tag '検索する'  %>
    <% end %>
    </div>

    <div class="all">
        <div class="allbooks">

        <% @books.each do |t| %>
            <div class="box books-container">

                <div class="book">
                <%# 投稿者：<%= link_to t.user.name, user_path(t.user.id) %>
                    <div class="title">
                        <a> <%= link_to t.title, book_path(t.id) %></a><br>
                        特徴：<%= t.point %>
                    </div>
                        
                <%# 映画化：<%= t.movie %>
                <%# 出版年：<%= t.year %>
                <%# 映画化、出版年は詳細ページに記載 %>
                    <div class="book-picture">
                        <%= image_tag t.image_url, size: "210x297" if t.image? %>
                    </div>
                </div>
                <div class="story">
                    <%= t.story %>
                </div>

            <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= link_to book_like_path(id: t.id, book_id: t.id), method: :delete do %>
                        <p>「読んだ」を取り消す <%= t.likes.count %></p>
                    <% end %>
                <% else %>
                    <%= link_to book_likes_path(id: t.id, book_id: t.id), method: :post do %>
                        <p>読んだ <%= t.likes.count %></p>
                    <% end %>
                <% end %>
            <% else %>
                <p>「読んだ」の数 : <%= t.likes.count %></p>
            <% end %>

            <% if user_signed_in? %>
                <% if current_user.already_wanted?(t) %>
                    <%= link_to book_want_path(id: t.id, book_id: t.id), method: :delete do %>
                        <p>「読んでみたい」を取り消す <%= t.wants.count %></p>
                    <% end %>
                <% else %>
                    <%= link_to book_wants_path(id: t.id, book_id: t.id), method: :post do %>
                        <p>読んでみたい <%= t.wants.count %></p>
                        <br>
                    <% end %>
                <% end %>
            <% else %>
                <p>「読んでみたい」の数 : <%= t.wants.count %></p>
            <% end %>
            <% if user_signed_in? %>
                <% if current_user.admin==true %> 
                    <%= t.created_at %>
                    <%# <%= link_to "詳細へ", book_path(t.id) %> 
                    <%= link_to "編集する", edit_book_path(t.id) %>
                    <%= button_to "削除する", book_path(t.id), method: :delete %>
                    <br>
                <%end%>
            <%end%>
            </div>

            <% end %>
        </div>
        <div class='box-ranking'>
            <div class="liked">
                <% rank=1 %>
                「読んだ」ランキング<br>
                    <% @liked.each do |t| %>
                        第<%= rank %>位 <a> <%= link_to t.title, book_path(t.id) %></a><br>
                        <% rank+=1 %>
                    <% end %>
                    <br>
            </div>
            <div class="wanted">
                <% rank=1 %>
                「読んでみたい」ランキング<br>
                <% @wanted.each do |t| %>
                        第<%= rank %>位 <a> <%= link_to t.title, book_path(t.id) %></a><br>
                        <% rank+=1 %>
                    <% end %>
            </div>
        </div>
    </div>
</html>

app/views/books/new.html.erb
<h1>Isaka kotaro</h1>
<h3>新刊投稿</h3>
<%= form_for @book do |f| %>

<%# # データ型がstringで自由記述の入力フォーム %>
  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title, :size => 30 %>
  </div>

<%# データ型がstringで選択式の入力フォーム %>
  <div class="field">
    <%= f.label :映画化  %>
    <%= f.select :movie, 
    [["している", "している"], 
    ["していない", "していない"], ], include_blank: "選択して下さい" %>
  </div>

<%# データ型がintegerで数字のみを入力するフォーム %>
  <div class="field">
    <%= f.label :出版年  %>
    <%= f.number_field :year, :size => 10 %>
  </div>

<%# データ型がtextで自由記述の入力フォーム %>
  <div class="field">
    <%= f.label :あらすじ（簡単に）  %>
    <%= f.text_area :story, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :特徴 %>
    <%= f.text_field :point, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "新刊を投稿する" %>
<% end %>

<%= link_to "一覧に戻る", books_path %>

app/views/books/show.html.erb
<div class="detail-all">
  <div class="title-show">
    <h2><p><%= @book.title %></p></h2>
  </div>

  <div class="detail">
    <div class="book-picture-show">
          <%= image_tag @book.image_url, size: "252x356.4" if @book.image? %>
    </div>
    <div class="exprain">
      映画化：<%= @book.movie %><br>
      出版年：<%= @book.year %><br>
      あらすじ:<p>&emsp;<%= @book.story %></p>
      <div class="yonda-or-yomitai">
        <div class="yonda">
          <% if user_signed_in? %>
            <% if current_user.already_liked?(@book) %>
              <%= link_to book_like_path(@book), method: :delete do %>
                「読んだ」を取り消す：<%= @book.likes.count %>
            <% end %>
            <% else %>
              <%= link_to book_likes_path(@book), method: :post do %>
                読んだ：<%= @book.likes.count %>
            <% end %>
            <% end %>
            <% else %>
              <p>「読んだ」の数 = <%= @book.likes.count %></p>
          <% end %>
        <% if user_signed_in? %>
          <% if current_user.admin==true %> 
            <%= link_to "編集する", edit_book_path(@book.id) %>
          <% end %>
        <% end %>
        </div>
        <div class="yomitai">
          <% if user_signed_in? %>
            <% if current_user.already_wanted?(@book) %>
              <%= link_to book_want_path(@book), method: :delete do %>
                「読んでみたい」を取り消す：<%= @book.wants.count %>
              <% end %>
            <% else %>
              <%= link_to book_wants_path(@book), method: :post do %>
                読んでみたい：<%= @book.wants.count %>
              <% end %>
            <% end %>
          <% else %>
            <p>「読んでみたい」の数 = <%= @book.wants.count %></p>
          <% end %>
        <% if user_signed_in? %>
          <% if current_user.admin==true %>
          <%= link_to "編集する", edit_book_path(@book.id) %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="user-show">
    <div class="read"> 
      <h3>読んだユーザー</h3>
      <% @book.liked_users.each do |user| %>
        <li>・<%= user.name %></li>
      <% end %>
    </div>

    <div class="want">
      <h3>読んでみたいユーザー</h3>
      <% @book.wanted_users.each do |user| %>
        <li>・<%= user.name %></li>
      <% end %>
    </div>

    <div class="comment-wrapper">
      <h3>コメント一覧</h3>
      <% @comments.each do |c| %>
        <div>
          <%= c.user.name unless c.user.blank? %>:<%= c.content %>
        </div>
      <%= button_to "削除する", book_comment_path(c.id), method: :delete %>
      <% end %>

      <% if user_signed_in? %>
        <%= form_with(model: [@book, @comment], local: true) do |f| %>
          <%= f.text_area :content %>
          <%= button_tag type: "submit" do %>
            <i class="far fa-comments"></i> コメントする
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/success.html.erb
<h1>Isaka kotaro</h1>

<div>

正常に編集されました

</div>

<%= link_to "一覧に戻る", books_path %>

app/views/perfumes/index.html.erb
<!DOCTYPE html> <!--この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head>
    <meta charset="utf-8">
    <title>香水診断スタート</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'perfumes', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    </head>

    <body>
    <div class="recommendation">        
        <div class="recommendation-inbox">
            <h2></h2>
        </div>
            <div class="h3">
                <h3>Are you ready?</h3>
            </div>
            <div class="start">
                <a><%= link_to "➡➡診断を始める", new_perfume_path %></a>
            </div>
        </div>
    </div>
    </body>
</html>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
            <div class="container-sindan">
                <div class="row">
                    <div class="Q1-3">
                        <div class="Q1">
                            <div class="col-12">
                                <p>Q1. 本は…</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "1", nil %>よく読む</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "2", nil %>あまり読まない</p>
                            </div>
                        </div>
                        <br>
                        <div class="Q2">
                            <div class="col-12">
                                <p>Q2. 伊坂幸太郎の本は…</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "1", nil %>読んだことがる</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "2", nil %>読んだことがない</p>
                            </div>
                        </div>
                        <br>
                        <div class="Q3">
                            <div class="col-12">
                                <p>Q3. どちらかというと…</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "1", nil %>忍耐強い方だ</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "2", nil %>新しいことに手を出す方だ</p>
                            </div>
                        </div>
                    </div>
                    <div class="Q4-6">
                        <div class="Q4">
                            <div class="col-12">
                                <p>Q4. 新しいことにチャレンジすることは…</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "1", nil %>好きな方だ</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "2", nil %>苦手な方だ</p>
                            </div>
                        </div>
                        <br>
                        <div class="Q5">
                            <div class="col-12">
                                <p>Q5. どちらかというと…</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "1", nil %>現実的な方だ</p>
                            </div>
                            <div class="col-6">
                                <p><%= f.check_box :question, {multiple: true}, "2", nil %>よく空想する方だ</p>
                            </div>
                        </div>
                         <div class="sindanbotan">
                            <%= f.submit "post" %>
                        </div>
                    </div>
                </div>
            </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>