config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books do
    resources :likes, only: [:create, :destroy]
    resources :wants, only: [:create, :destroy]
    resources :comments
    resources :results
    
  end

  resources :perfumes


    root 'books#index'

  get "books/:id/success" => "books#success", as:"success_book"
  get "books/:book_id/likes" => 'likes#create'
  get "books/:book_id/likes/:id" => 'likes#destroy'

  get "books/:book_id/wants" => 'wants#create'
  get "books/:book_id/wants/:id" => 'wants#destroy'

  post 'perfumes/:num' => 'perfumes#result'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :wants, dependent: :destroy
    has_many :wanted_users, through: :wants, source: :user

    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/perfume.rb
class Perfume < ApplicationRecord
    belongs_to :user 
end

app/models/result.rb
class Result < ApplicationRecord

    belongs_to :user 
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_books, through: :likes, source: :book

  has_many :wants, dependent: :destroy
  has_many :wanted_books, through: :wants, source: :book

  has_many :comments, dependent: :destroy

  # has_many :perfumes, dependent: :destroy
  # has_many :resulted_perfumes, through: :results, source: :book

  has_many :results, dependent: :destroy
  has_many :perfumes, dependent: :destroy


  def already_liked?(book)
    self.likes.exists?(book_id: book.id)
  end

  def already_wanted?(book)
    self.wants.exists?(book_id: book.id)
  end

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def index
        @books = Book.all
        @liked = Book.includes(:liked_users).limit(3).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
        @wanted = Book.includes(:wanted_users).limit(3).sort {|a,b| b.wanted_users.size <=> a.wanted_users.size}
 
     if params[:search] == nil
         @books= Book.all
     elsif params[:search] == ''
         @books= Book.all
     else
          #部分検索
         @books = Book.where("movie LIKE ? or point LIKE?",'%' + params[:search] + '%','%' + params[:search] + '%')
     end

    end
      
    def new
        @book = Book.new
    end
    
    def create
        book = Book.new(book_params)
        book.user_id = current_user.id
        if book.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @book = Book.find(params[:id])

        @comments = @book.comments
        @comment = Comment.new
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        book = Book.find(params[:id])
        if book.update(book_params)
            redirect_to :action => "success", :id => book.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        book = Book.find(params[:id])
        # book変数の中にBook.find(params[:id])が代入されている
        book.destroy
        # それをdestroyする
        redirect_to action: :index
    end

    private
    def book_params
        params.require(:book).permit(:story, :movie, :year, :title, :image, :point)
    end

end

# commentコントローラーとcommentコントローラーを削除し、やり直す

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(book_id: params[:book_id]) #user_idとbook_idの二つを代入
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(book_id: params[:book_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
        @perfumes = Perfume.all
    end

end

app/controllers/wants_controller.rb
class WantsController < ApplicationController

    def create
        want = current_user.wants.create(book_id: params[:book_id]) #user_idとbook_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        want = Want.find_by(book_id: params[:book_id], user_id: current_user.id)
        want.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Isaka</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
</head>

<div class="footerFixed">
  <body>
  <header>
    <div id="header-list">
      <div id="header-logo">
        <h1><li><%= link_to "Isaka kotaro", books_path %></li></h1>
      </div>
      <div id="header-content">
        <nav>
          <ul>
            <% if user_signed_in? %>
              <a><li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete,class: "button content" %></li></a>
            <% else %>
              <a><li><%= link_to '新規登録', new_user_registration_path,class: "content" %></li></a>
              <a><li><%= link_to "ログイン", new_user_session_path,class: "content" %></li></a>
            <% end %>
            
            <% if user_signed_in? %>
            <% if current_user.admin==true %>
            <a><li><%= link_to "新規投稿へ", new_book_path,class: "content" %></li></a>
            <% end %>
      
            <a><li><%= link_to "おすすめの本診断", perfumes_path(current_user.id),class: "content" %></li></a>
            <a><li><%= link_to "マイページへ", user_path(current_user.id),class: "content" %></li></a>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
    <p>Copyright © Syunsuke Maruhashi All Rights Reserved.</p>
  </footer>
  </body>
</div>
</html>